require 'ipaddress_2'

module Wgconf
  class ConfBuilder
    include Wgconf::Utils

    def initialize(net_config)
      @net_config = net_config
    end

    def conf_for(node)
      buffer = conf_header(node)

      @net_config.nodes.each do |pair|
        next if node.name == pair.name
        next if node.client_only && pair.client_only

        buffer << conf_pair(node, pair)
      end
      buffer
    end

    private

    # rubocop:disable Metrics/AbcSize
    def conf_pair(node, pair)
      wg_port = pair.listen_port || @net_config.listen_port
      buffer = "\n[Peer]\n# #{pair.name}\nPublicKey = #{wg_pubkey(pair.private_key)}\n"\
               "PresharedKey = #{@net_config.get_psk(node.name, pair.name)}\n"\
               "AllowedIPs = #{pair.addresses.join(', ')}"
      if pair.gateway
        buffer << ', 0.0.0.0/0' if @net_config.ipv4?
        buffer << ', ::/0' if @net_config.ipv6?
      end
      buffer << "\n"
      if !pair.client_only and pair.listen_endpoint and \
        ((!IPAddress::IPv4::parse_classful(pair.listen_endpoint).c?) or
        (node.listen_endpoint and IPAddress::IPv4::parse_classful(node.listen_endpoint).c?))
        buffer << "Endpoint = #{pair.listen_endpoint}:#{wg_port}\n"
      end
      if node.client_only && !pair.client_only && @net_config.persistent_keepalive.positive?
        buffer << "PersistentKeepalive = #{@net_config.persistent_keepalive}\n"
      end
      buffer
    end
    # rubocop:enable Metrics/AbcSize

    def conf_header(node)
      buffer = "# Generated by wgconf at #{Time.now.getutc}, node: #{node.name}\n\n[Interface]\n"
      node.addresses.each do |address|
        buffer << "Address = #{@net_config.interface_cidr(address)}\n"
      end
      buffer << "ListenPort = #{node.listen_port || @net_config.listen_port}\n"
      buffer << "PrivateKey = #{node.private_key}\n"
    end
  end
end
